# Generated by Django 4.0.4 on 2022-05-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdomainselectors',
            name='domain_for_selector',
            field=models.CharField(default='', max_length=200),
        ),
    ]
